### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by MrZeze1** [cs3cx4g/RTLS-UWB#1]
![image](https://user-images.githubusercontent.com/62024035/113481365-c045bd80-94cb-11eb-8fab-50d7399cde59.png)
您好，请问这个怎么解决呀

**Comment by Mereithhh** [comment]
字面意思，稳妥一点选第二项，下一个和我一样的4.7.2装上就好了。

MrZeze1 ***@***.***>于2021年4月3日 周六下午10:28写道：
