### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by MrZeze1** [cs3cx4g/RTLS-UWB#2]
请问这个编写只能用C++嘛，可以用C吗，小白想做UWB，希望能够指导指导

**Comment by Mereithhh** [comment]
这个使用C# 写的哈，相关语法网上搜就好，你会c语言的话C#学学就会了，大同小异的。

**Comment by MrZeze1** [comment]
UWB的定位算法也是C#吗。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月6日(周二) 晚上6:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mereithhh/RTLS-UWB] 语言问题 (#2)




 
这个使用C# 写的哈，相关语法网上搜就好，你会c语言的话C#学学就会了，大同小异的。
 
&mdash;

**Comment by Mereithhh** [comment]
是的，语言只是工具，C#可以很简单的转换成C语言的形式。我的博客上应该有用到的公式，用C语言表达就行了。实际上就是简单的坐标换算和解方程组，通过四个距离解x,y,z轴的坐标，真的很简单。

MrZeze1 ***@***.***> 于2021年4月6日周二 下午6:58写道：

**Comment by Mereithhh** [comment]
https://www.mereith.com/2020/01/23/%E5%9F%BA%E4%BA%8EUWB%E7%9A%84%E5%AE%A4%E5%86%85%E4%B8%89%E7%BB%B4%E5%AE%9A%E4%BD%8D/

**Comment by MrZeze1** [comment]
博主您好，我想做UWB方向但是没有啥基础，请问都需要学什么呢，都要掌握什么知识呢，十分感谢您
